# Generated by Django 2.1.2 on 2018-10-23 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_desc', models.TextField()),
                ('cat_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('item_desc', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_veg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='order_desc',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurent',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='some@email.com', max_length=100, unique=True)),
                ('password', models.CharField(default='pass123', max_length=500)),
                ('user_created_at', models.DateField(default=django.utils.timezone.now)),
                ('user_updated_at', models.DateField(auto_now=True)),
                ('user_isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
